{
  "mitigation": "To mitigate this feature on Red Hat Quay keep the invoice generation feature disabled, as it is by default.",
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Affected",
      "package_name": "quay-registry-container",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2021-04-01T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2021-28678 python-pillow: improper check in BlpImagePlugin can lead to DoS",
    "id": "1958263",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1958263"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2021-28678",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}