{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Tower 3",
      "fix_state": "Not affected",
      "package_name": "rabbitmq-server",
      "cpe": "cpe:/a:redhat:ansible_tower:3"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 7 (Kilo)",
      "fix_state": "Under investigation",
      "package_name": "rabbitmq-server",
      "cpe": "cpe:/a:redhat:openstack:7"
    },
    {
      "product_name": "Red Hat OpenStack Platform 10 (Newton)",
      "fix_state": "Under investigation",
      "package_name": "rabbitmq-server",
      "cpe": "cpe:/a:redhat:openstack:10"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Under investigation",
      "package_name": "rabbitmq-server",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16 (Train)",
      "fix_state": "Under investigation",
      "package_name": "rabbitmq-server",
      "cpe": "cpe:/a:redhat:openstack:16"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2021-05-13T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2021-22116 rabbitmq-server: improper input validation may lead to DoS",
    "id": "1961638",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1961638"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.9",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2021-22116",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": [
    "https://tanzu.vmware.com/security/cve-2021-22116"
  ]
}